chainables/chainable

src/main/java/com/github/martinsawicki/collections/Chainables.java, src/test/java/com/github/martinsawicki/collections/ChainableTest.java
```
equals()
equalsEither()
apply()
applyAsYouGo()
size() / count()
```
=> Initial basic APIs

src/main/java/com/github/martinsawicki/collections/Chainables.java, src/test/java/com/github/martinsawicki/collections/ChainableTest.java
```
stream() / toStream()
toArray()
where(), whereEither(), notWhere()
withoutNull()
containsSubarray(), containsAll(), contains(), containsAny()
=> Further Chainable APIs

src/main/java/com/github/martinsawicki/collections/Chainables.java, src/test/java/com/github/martinsawicki/collections/ChainableTest.java
notBefore(), notBeforeValue(), atLeast(), atMost(), max(), min(), reverse(), split(), before(), beforeValue(), asLongAs(), asLongAsValue()
=> More Chainable API

README.md, pom.xml, src/main/java/com/github/martinsawicki/collections/Chainables.java, src/test/java/com/github/martinsawicki/collections/ChainableTest.java, src/test/java/com/github/martinsawicki/collections/PerfTest.java
- `chain(), chainIf(), interleave()`
- misc docs updates
- initial JMH benchmarks
=> More Chainable API and docs updates

src/main/java/com/github/martinsawicki/chainable/Chainable.java, src/main/java/com/github/martinsawicki/chainable/ChainableTree.java, src/main/java/com/github/martinsawicki/chainable/ChainableTrees.java, src/main/java/com/github/martinsawicki/chainable/Chainables.java, src/test/java/com/github/martinsawicki/chainable/ChainableTest.java, src/test/java/com/github/martinsawicki/chainable/ChainableTreeTest.java
- `parent()`
- `children()`, `withChildren()`
- `values()`
- unseeded `chain()` support
=> Initial ChainableTree

src/main/java/com/github/martinsawicki/chainable/ChainableTree.java, src/main/java/com/github/martinsawicki/chainable/ChainableTrees.java, src/test/java/com/github/martinsawicki/chainable/ChainableTreeTest.java
- `breadthFirst()`, `breadthFirstNotBelow()`
=> ChainableTree breadthFirst traversal

src/main/java/com/github/martinsawicki/chainable/Chainable.java, src/main/java/com/github/martinsawicki/chainable/ChainableTree.java, src/main/java/com/github/martinsawicki/chainable/ChainableTrees.java, src/main/java/com/github/martinsawicki/chainable/Chainables.java, src/test/java/com/github/martinsawicki/chainable/ChainableTest.java, src/test/java/com/github/martinsawicki/chainable/ChainableTreeTest.java
`Chainable`
- `fromIterator()`
- indexed `chain()`
- `depthFirstNotBelow()`
=> Chainable tweaks

README.md, src/main/java/com/github/martinsawicki/chainable/Chainable.java, src/main/java/com/github/martinsawicki/chainable/ChainableTree.java, src/main/java/com/github/martinsawicki/chainable/ChainableTrees.java, src/main/java/com/github/martinsawicki/chainable/Chainables.java, src/test/java/com/github/martinsawicki/chainable/ChainableTest.java, src/test/java/com/github/martinsawicki/chainable/ChainableTreeTest.java
- `.depthFirst()`
- `.successors()`
=> More ChainableTree API

README.md, src/main/java/com/github/martinsawicki/chainable/ChainableTree.java, src/main/java/com/github/martinsawicki/chainable/ChainableTrees.java, src/test/java/com/github/martinsawicki/chainable/ChainableTest.java, src/test/java/com/github/martinsawicki/chainable/ChainableTreeTest.java
=> More API and README updates

README.md, src/main/java/com/github/martinsawicki/chainable/Chainable.java, src/main/java/com/github/martinsawicki/chainable/ChainableTree.java, src/main/java/com/github/martinsawicki/chainable/ChainableTrees.java, src/test/java/com/github/martinsawicki/chainable/ChainableTreeTest.java
`ChainableTree`:
- `siblings()`
- `firstWhere()`
- `descendants()`
- `ancestors()`
- `isUnder()`
- `terminals()`
- `upAsLongAs()`
- `upUntil()`
- `upUntilEither()`
=> More ChainableTree API and README tweaks

src/main/java/com/github/chainables/chainable/Chainable.java, src/main/java/com/github/chainables/chainable/ChainableTree.java, src/main/java/com/github/chainables/chainable/ChainableTrees.java, src/main/java/com/github/chainables/chainable/Chainables.java, src/test/java/com/github/chainables/chainable/ChainableTreeTest.java
- `clone()`
- `notWhere()`
- `notBelowWhere()`
- `withRoot()`
=> Misc Tree API and bug fixes

pom.xml, src/main/java/com/github/chainables/chainable/Chainable.java, src/main/java/com/github/chainables/chainable/ChainableTree.java, src/main/java/com/github/chainables/chainable/ChainableTrees.java, src/main/java/com/github/chainables/chainable/Chainables.java, src/test/java/com/github/chainables/chainable/ChainableTest.java, src/test/java/com/github/chainables/chainable/ChainableTreeTest.java
`Chainable`
- `isCountAtLeast()`, `isCountAtMost()`, `isCountExactly()`
- `isAbove()`
- `firstWithValue()`
- `isBelow()`
- `predecessor()`, `successor()`
- `clone()`
- `notWhere()`
- depth-aware `withChildValueExtractor()`
- `withRoot()`
- `notBelowWhere()`
- `where()`
=> Release v0.5.0 (#44)

pom.xml, src/main/java/com/github/chainables/chainable/Chainable.java, src/main/java/com/github/chainables/chainable/Chainables.java, src/test/java/com/github/chainables/chainable/ChainableTest.java
- Stream interop enhancements
- upper-/lower-bounding of generics
- caching improvements
- `Chainable#get()`
=> Next version kickoff

pom.xml
Meeting Maven Central requirements
=> release 0.5.1

pom.xml
Additional POM enhancements to adhere to Maven Central requirements
=> release v0.5.2

.gitignore, README.md, pom.xml, src/main/java/com/github/chainables/chainable/Chainable.java, src/main/java/com/github/chainables/chainable/ChainableTree.java, src/main/java/com/github/chainables/chainable/Chainables.java, src/test/java/com/github/chainables/chainable/ChainableTest.java, src/test/java/com/github/chainables/chainable/ChainableTreeTest.java
* Chainable.split()
* readme encancements
Co-authored-by: Martin Sawicki <msawicki@alumni.princeton.edu>
=> v0.6.0 shipped

src/main/java/com/github/chainables/chainable/Chainable.java, src/main/java/com/github/chainables/chainable/ChainableTree.java, src/main/java/com/github/chainables/chainable/ChainableTrees.java, src/main/java/com/github/chainables/chainable/Chainables.java, src/test/java/com/github/chainables/chainable/ChainableTest.java
- more javadocs
- `Chainable#toSet()`
=> More javadocs + misc enhancements

pom.xml, src/main/java/com/github/chainables/chainable/Chainable.java, src/main/java/com/github/chainables/chainable/ChainableTree.java, src/main/java/com/github/chainables/chainable/ChainableTrees.java, src/main/java/com/github/chainables/chainable/Chainables.java, src/test/java/com/github/chainables/chainable/ChainableTest.java
* more javadocs
* Chainable#toSet()
=> release v0.7.1 (#62)

pom.xml, src/main/java/com/github/chainables/chainable/Chainable.java, src/main/java/com/github/chainables/chainable/ChainableTrees.java, src/main/java/com/github/chainables/chainable/Chainables.java, src/test/java/com/github/chainables/chainable/ChainableTest.java
including:
- bug fix in `Chainable#range()`
- static `interleave()`
=> Starting v0.10.1

pom.xml, src/main/java/com/github/chainables/chainable/Chainable.java, src/main/java/com/github/chainables/chainable/ChainableTrees.java, src/main/java/com/github/chainables/chainable/Chainables.java, src/test/java/com/github/chainables/chainable/ChainableTest.java
- new static `interleave()`
- bug fix in `Chainable#range()` when start is the same or greater than end
=> Release v0.10.1 (#81)
